package br.com.diginteligente.diagnostico;

import android.app.Activity;import android.app.AlertDialog;import android.graphics.Canvas;import android.graphics.Color;import android.graphics.Paint;import android.graphics.RectF;import android.graphics.Typeface;import android.graphics.drawable.GradientDrawable;import android.os.Bundle;import android.view.Gravity;import android.view.View;import android.view.ViewGroup;import android.view.animation.OvershootInterpolator;import android.widget.Button;import android.widget.GridLayout;import android.widget.LinearLayout;import android.widget.ScrollView;import android.widget.TextView;import java.util.ArrayList;import java.util.Collections;import java.util.Comparator;import java.util.List;

public class DominoActivity extends Activity{
 private final List<Tile>[]hands=new ArrayList[]{new ArrayList<>(),new ArrayList<>(),new ArrayList<>(),new ArrayList<>()};private final List<Tile>chain=new ArrayList<>();private GridLayout board,hand;private TextView status,topCount,leftCount,rightCount,score;private int left=-1,right=-1,current,passes;private boolean ended;
 @Override protected void onCreate(Bundle b){super.onCreate(b);build();newMatch();}
 private void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(8),dp(10),dp(8),dp(8));root.setBackgroundColor(0xff06472f);
  LinearLayout head=new LinearLayout(this);TextView title=txt("DOMINO",24,Color.WHITE,true);head.addView(title,new LinearLayout.LayoutParams(0,-2,1));Button help=button("?");help.setOnClickListener(v->tutorial());head.addView(help,new LinearLayout.LayoutParams(dp(48),dp(44)));root.addView(head);score=txt("",12,0xffc9f8e6,false);root.addView(score);status=txt("",15,Color.WHITE,true);status.setPadding(0,dp(4),0,dp(6));root.addView(status);
  topCount=opponent("Lia",0xffd45668);topCount.setGravity(Gravity.CENTER);root.addView(topCount,new LinearLayout.LayoutParams(-1,dp(48)));
  LinearLayout middle=new LinearLayout(this);leftCount=opponent("Beto",0xff3f83c5);leftCount.setGravity(Gravity.CENTER);middle.addView(leftCount,new LinearLayout.LayoutParams(dp(62),-1));
  ScrollView tableScroll=new ScrollView(this);board=new GridLayout(this);board.setColumnCount(5);board.setPadding(dp(7),dp(7),dp(7),dp(7));board.setBackground(round(0xff033522,10,0xff278d65));tableScroll.addView(board,new ViewGroup.LayoutParams(-1,-2));middle.addView(tableScroll,new LinearLayout.LayoutParams(0,dp(310),1));
  rightCount=opponent("Nina",0xff9a62bd);rightCount.setGravity(Gravity.CENTER);middle.addView(rightCount,new LinearLayout.LayoutParams(dp(62),-1));root.addView(middle);
  TextView me=txt("VOCE",12,0xffc9f8e6,true);me.setGravity(Gravity.CENTER);root.addView(me);hand=new GridLayout(this);hand.setColumnCount(7);root.addView(hand,new LinearLayout.LayoutParams(-1,dp(94)));LinearLayout actions=new LinearLayout(this);Button pass=button("Passar");pass.setOnClickListener(v->playerPass());Button fresh=button("Nova partida");fresh.setOnClickListener(v->newMatch());actions.addView(pass,new LinearLayout.LayoutParams(0,-2,1));actions.addView(fresh,new LinearLayout.LayoutParams(0,-2,1));root.addView(actions);setContentView(root);if(!getSharedPreferences("dig_games",MODE_PRIVATE).getBoolean("domino4_help",false))root.postDelayed(this::tutorial,350);}
 private TextView opponent(String name,int color){TextView v=txt(name+"\n▯ ▯ ▯",12,Color.WHITE,true);v.setBackground(round(color,22,Color.WHITE));v.setPadding(dp(4),dp(4),dp(4),dp(4));return v;}
 private void newMatch(){for(List<Tile>h:hands)h.clear();chain.clear();left=right=-1;passes=0;ended=false;List<Tile>deck=new ArrayList<>();for(int a=0;a<=6;a++)for(int b=a;b<=6;b++)deck.add(new Tile(a,b));Collections.shuffle(deck);for(int i=0;i<28;i++)hands[i%4].add(deck.get(i));int owner=0;Tile start=null;for(int value=6;value>=0&&start==null;value--)for(int p=0;p<4;p++)for(Tile t:hands[p])if(t.a==value&&t.b==value){owner=p;start=t;break;}hands[owner].remove(start);chain.add(start);left=start.a;right=start.b;current=(owner+1)%4;render();if(current!=0)status.postDelayed(this::cpuTurns,550);}
 private void render(){board.removeAllViews();for(int i=0;i<chain.size();i++){Tile t=chain.get(i);DominoView v=new DominoView(t,i%5==4);GridLayout.LayoutParams lp=new GridLayout.LayoutParams();lp.width=0;lp.height=dp(i%5==4?70:76);lp.columnSpec=GridLayout.spec(GridLayout.UNDEFINED,1f);lp.setMargins(dp(2),dp(2),dp(2),dp(2));board.addView(v,lp);}hand.removeAllViews();for(Tile t:new ArrayList<>(hands[0])){DominoView v=new DominoView(t,false);v.setOnClickListener(x->playerMove(t,v));GridLayout.LayoutParams lp=new GridLayout.LayoutParams();lp.width=0;lp.height=dp(88);lp.columnSpec=GridLayout.spec(GridLayout.UNDEFINED,1f);lp.setMargins(dp(2),dp(2),dp(2),dp(2));hand.addView(v,lp);}topCount.setText("Lia\n"+backs(hands[2].size()));leftCount.setText("Beto\n"+backs(hands[1].size()));rightCount.setText("Nina\n"+backs(hands[3].size()));score.setText("Pontas: "+left+" e "+right+"  |  Pecas na mesa: "+chain.size()+"  |  Geral: "+getSharedPreferences("dig_games",MODE_PRIVATE).getInt("total_points",0)+" pts");if(!ended)status.setText(current==0?"Sua vez: escolha uma peca compativel":"Vez de "+name(current)+"...");}
 private String backs(int n){StringBuilder s=new StringBuilder();for(int i=0;i<Math.min(n,7);i++)s.append("▯ ");return s.toString();}private String name(int p){return p==0?"Voce":p==1?"Beto":p==2?"Lia":"Nina";}
 private void playerMove(Tile t,View v){if(ended||current!=0)return;if(!can(t)){v.animate().translationX(dp(7)).setDuration(70).withEndAction(()->v.animate().translationX(0).setDuration(90)).start();status.setText("Essa peca nao combina com as pontas");return;}hands[0].remove(t);place(t);v.animate().scaleX(1.2f).scaleY(1.2f).rotationY(180).setDuration(220).setInterpolator(new OvershootInterpolator()).start();passes=0;next();}
 private void playerPass(){if(ended||current!=0)return;for(Tile t:hands[0])if(can(t)){status.setText("Voce possui uma jogada valida");return;}passes++;if(passes>=4){blocked();return;}current=1;render();status.postDelayed(this::cpuTurns,500);}
 private void cpuTurns(){if(ended||current==0)return;List<Tile>legal=new ArrayList<>();for(Tile t:hands[current])if(can(t))legal.add(t);if(legal.isEmpty()){passes++;}else{legal.sort(Comparator.comparingInt((Tile t)->t.a+t.b+(t.a==t.b?5:0)).reversed());Tile play=legal.get(0);hands[current].remove(play);place(play);passes=0;}if(checkEnd())return;current=(current+1)%4;render();if(current!=0)status.postDelayed(this::cpuTurns,520);else if(passes>=4)blocked();}
 private void next(){if(checkEnd())return;current=1;render();status.postDelayed(this::cpuTurns,520);}
 private boolean can(Tile t){return t.a==left||t.b==left||t.a==right||t.b==right;}private void place(Tile t){if(t.a==left){chain.add(0,new Tile(t.b,t.a));left=t.b;}else if(t.b==left){chain.add(0,t);left=t.a;}else if(t.a==right){chain.add(t);right=t.b;}else{chain.add(new Tile(t.b,t.a));right=t.a;}}
 private boolean checkEnd(){for(int p=0;p<4;p++)if(hands[p].isEmpty()){finishGame(p,"bateu primeiro");return true;}if(passes>=4){blocked();return true;}return false;}private void blocked(){int winner=0,best=sum(hands[0]);for(int p=1;p<4;p++){int s=sum(hands[p]);if(s<best){best=s;winner=p;}}finishGame(winner,"venceu a partida bloqueada");}private int sum(List<Tile>h){int s=0;for(Tile t:h)s+=t.a+t.b;return s;}
 private void finishGame(int winner,String reason){ended=true;int pts=winner==0?50:0;if(winner==0){int old=getSharedPreferences("dig_games",MODE_PRIVATE).getInt("total_points",0);getSharedPreferences("dig_games",MODE_PRIVATE).edit().putInt("total_points",old+pts).apply();}render();new AlertDialog.Builder(this).setTitle(winner==0?"Voce venceu!":name(winner)+" venceu").setMessage(name(winner)+" "+reason+(pts>0?". +50 pontos":".")).setPositiveButton("Nova partida",(d,w)->newMatch()).setNegativeButton("Fechar",null).show();}
 private void tutorial(){getSharedPreferences("dig_games",MODE_PRIVATE).edit().putBoolean("domino4_help",true).apply();new AlertDialog.Builder(this).setTitle("Como jogar").setMessage("Quatro jogadores recebem sete pecas. A maior dupla comeca.\n\nToque em uma peca que combine com uma das duas pontas. Quem terminar primeiro vence. Se todos passarem, ganha a menor soma.").setPositiveButton("Jogar",null).show();}
 private Button button(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);return b;}private TextView txt(String s,int z,int c,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);if(bold)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return t;}private GradientDrawable round(int fill,int radius,int stroke){GradientDrawable d=new GradientDrawable();d.setColor(fill);d.setCornerRadius(dp(radius));if(stroke!=0)d.setStroke(dp(1),stroke);return d;}private int dp(int n){return(int)(n*getResources().getDisplayMetrics().density+.5f);}private float dpf(float n){return n*getResources().getDisplayMetrics().density;}
 private class DominoView extends View{Tile t;boolean turn;Paint p=new Paint(Paint.ANTI_ALIAS_FLAG);DominoView(Tile t,boolean turn){super(DominoActivity.this);this.t=t;this.turn=turn;setLayerType(View.LAYER_TYPE_SOFTWARE,null);setElevation(dp(6));}@Override protected void onDraw(Canvas c){float w=getWidth(),h=getHeight();p.setShadowLayer(dp(2),0,dp(2),0x66000000);p.setColor(0xfffffff8);c.drawRoundRect(new RectF(dp(2),dp(2),w-dp(2),h-dp(5)),dp(7),dp(7),p);p.clearShadowLayer();p.setColor(0xff202326);p.setStrokeWidth(dp(2));c.drawLine(dp(6),h/2,w-dp(6),h/2,p);dots(c,t.a,w/2,h/4,Math.min(w,h/2)*.28f);dots(c,t.b,w/2,h*.75f,Math.min(w,h/2)*.28f);}void dots(Canvas c,int v,float x,float y,float s){p.setColor(0xff17191b);float[][]a={{0,0},{-1,-1},{1,1},{-1,1},{1,-1},{-1,0},{1,0}};int[][]m={{},{0},{1,2},{1,0,2},{1,2,3,4},{1,2,3,4,0},{1,2,3,4,5,6}};for(int i:m[v])c.drawCircle(x+a[i][0]*s,y+a[i][1]*s,dpf(2.8f),p);}}
 private static class Tile{int a,b;Tile(int a,int b){this.a=a;this.b=b;}}
}
