package br.com.diginteligente.diagnostico;

import android.app.Activity;import android.app.AlertDialog;import android.graphics.Color;import android.os.Bundle;import android.view.Gravity;import android.view.View;import android.widget.Button;import android.widget.GridLayout;import android.widget.LinearLayout;import android.widget.TextView;import java.util.ArrayList;import java.util.Collections;import java.util.List;

public class SolitaireActivity extends ImmersiveActivity{
 private final List<Card>deck=new ArrayList<>();private final List<Card>[]piles=new ArrayList[]{new ArrayList<>(),new ArrayList<>(),new ArrayList<>(),new ArrayList<>()};private LinearLayout[]views=new LinearLayout[4];private TextView status;private int selected=-1;
 @Override protected void onCreate(Bundle b){super.onCreate(b);build();newGame();}
 private void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(12),dp(18),dp(12),dp(12));root.setBackgroundColor(0xff285a46);TextView title=text("PACIENCIA 3D",26,Color.WHITE);root.addView(title);status=text("",15,0xffe5fff4);root.addView(status);LinearLayout table=new LinearLayout(this);for(int i=0;i<4;i++){final int n=i;views[i]=new LinearLayout(this);views[i].setOrientation(LinearLayout.VERTICAL);views[i].setGravity(Gravity.BOTTOM);views[i].setPadding(dp(2),dp(4),dp(2),dp(4));views[i].setOnClickListener(v->tapPile(n));table.addView(views[i],new LinearLayout.LayoutParams(0,dp(350),1));}root.addView(table);Button deal=new Button(this);deal.setText("Distribuir nova linha");deal.setOnClickListener(v->deal());root.addView(deal);Button fresh=new Button(this);fresh.setText("Novo jogo");fresh.setOnClickListener(v->newGame());root.addView(fresh);setContentView(root);}
 private void newGame(){deck.clear();for(List<Card>p:piles)p.clear();for(int s=0;s<4;s++)for(int v=1;v<=13;v++)deck.add(new Card(s,v));Collections.shuffle(deck);selected=-1;deal();}
 private void deal(){if(deck.isEmpty()){status.setText("Monte vazio: elimine cartas ou mova para espacos");checkWin();return;}for(int i=0;i<4&&!deck.isEmpty();i++)piles[i].add(deck.remove(0));selected=-1;render();}
 private void tapPile(int n){if(piles[n].isEmpty()){if(selected>=0&&!piles[selected].isEmpty()){Card c=piles[selected].remove(piles[selected].size()-1);piles[n].add(c);selected=-1;render();}return;}Card top=top(n);boolean removable=false;for(int i=0;i<4;i++)if(i!=n&&!piles[i].isEmpty()&&top(i).suit==top.suit&&top(i).value>top.value)removable=true;if(removable){View card=views[n].getChildAt(views[n].getChildCount()-1);card.animate().rotationY(180).alpha(0).setDuration(220).withEndAction(()->{piles[n].remove(piles[n].size()-1);selected=-1;render();checkWin();}).start();}else{selected=n;status.setText("Carta selecionada. Toque em um espaco vazio para mover.");render();}}
 private Card top(int n){return piles[n].get(piles[n].size()-1);}private void checkWin(){int count=0;for(List<Card>p:piles)count+=p.size();if(deck.isEmpty()&&count==4){int old=getSharedPreferences("dig_games",MODE_PRIVATE).getInt("total_points",0);getSharedPreferences("dig_games",MODE_PRIVATE).edit().putInt("total_points",old+30).apply();new AlertDialog.Builder(this).setTitle("Vitoria").setMessage("Restaram quatro cartas. +30 pontos").setPositiveButton("Novo jogo",(d,w)->newGame()).show();}}
 private void render(){for(int i=0;i<4;i++){views[i].removeAllViews();int start=Math.max(0,piles[i].size()-6);for(int j=start;j<piles[i].size();j++){Card c=piles[i].get(j);TextView v=text(c.name(),18,c.red()?0xffd7354a:0xff17212b);v.setGravity(Gravity.CENTER);v.setBackgroundColor(i==selected&&j==piles[i].size()-1?0xffffd166:Color.WHITE);v.setElevation(dp(6));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(48));lp.setMargins(dp(2),dp(2),dp(2),dp(2));views[i].addView(v,lp);}}status.setText("Monte: "+deck.size()+" | Remova carta menor quando houver outra maior do mesmo naipe.");}
 private TextView text(String s,int z,int c){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);t.setPadding(dp(4),dp(5),dp(4),dp(5));return t;}private int dp(int n){return(int)(n*getResources().getDisplayMetrics().density+.5f);}private static class Card{int suit,value;Card(int s,int v){suit=s;value=v;}boolean red(){return suit==1||suit==2;}String name(){String[]vs={"","A","2","3","4","5","6","7","8","9","10","J","Q","K"};String[]ss={"♠","♥","♦","♣"};return vs[value]+ss[suit];}}
}
